# SHA1 hash of unmodified Defender.exe
defender_sha1 = "a23654a525b018be4a2b868d3679b48894e67162"

# Offset of section .h3mf85n, the code section of Defender.exe, equals to 
#   VirtualAddress - PointerToRawData
code_offset = 0x400C00

# Base address in memory, byte length and key of encrypted blocks. Keys were obtained from plaintext
# code or during debugging session. When key is not available, an expected signature of plaintext
# must be given for a brute force attack.
[[blocks]]
base = 0x0040219a
length = 0xbf3
key = 0x5A5A86F3
enc_dec_jump = 0x004020b6
# jmp 0x00402192
jump_rewrite = [0xe9, 0xd7, 0x00, 0x00, 0x00]


[[blocks]]
base = 0x004034dd
length = 0xd20
key = 0x2bca6179
enc_dec_jump = 0x00403405
# jmp 0x004034d5
jump_rewrite = [0xe9, 0xcb, 0x00, 0x00, 0x00]

[[blocks]]
base = 0x00401906
length = 0x30a
key = 0x0513B5C7
enc_dec_jump = 0x0040177f
# jmp 0x004018fe
jump_rewrite = [0xe9, 0x7a, 0x01, 0x00, 0x00]

[[blocks]]
base = 0x00402ff6
length = 0xec
key = 0xad7c194b
enc_dec_jump = 0x00402f1e
# jmp 0x00402fee
jump_rewrite = [0xe9, 0xcb, 0x00, 0x00, 0x00]


[[blocks]]
base = 0x00401fed
length = 0x92
# key = 0x8ed105c2
brute_force = true
critical = true
signature = [ 
    0xb8, 0x7f, 0x20, 0x40, 0x00,                   # MOV EAX, 0x0040207f
    0x89, 0x05, 0xe6, 0x1f, 0x40, 0x00,             # MOV dword ptr [0x00401fe6], EAX
    0xc7, 0x45, 0xfc, 0x00, 0x00, 0x00, 0x00,       # MOV dword ptr [EBP-0x4], 0x0
    0xe9, 0x6c, 0xfe, 0xff, 0xff                    # JMP 0x00401ee7
]
enc_dec_jump = 0x00401eeb
# jmp 0x00401fe5
jump_rewrite = [0xe9, 0xf5, 0x00, 0x00, 0x00]

[[blocks]]
base = 0x00401e32
length = 0x84
# key = 0xb14ac01a
brute_force = true
critical = true
signature = [
    0xb8, 0xb6, 0x1e, 0x40, 0x00,                   # MOV EAX, 0x00401eb6
    0x89, 0x05, 0x2b, 0x1e, 0x40, 0x00,             # MOV dword ptr [0x00401e2b], EAX
    0xC7, 0x45, 0xFC, 0x00, 0x00, 0x00, 0x00,       # MOV dword ptr [EBP-0x4], 0x0
    0xe9, 0x9e, 0xfe, 0xff, 0xff                    # JMP 0x00401d50
]
enc_dec_jump = 0x00401d54
# jmp 0x00401e2a
jump_rewrite = [0xe9, 0xd1, 0x00, 0x00, 0x00]

[[blocks]]
base = 0x00403335
length = 0x99
key = 0x9371d0a9
enc_dec_jump = 0x0040325d
# jmp 0x0040332d
jump_rewrite = [0xe9, 0xcb, 0x00, 0x00, 0x00]

[watchdog]
base = 0x00403075
rewrite = [
    0x90, 0x90,                                             # NOP, NOP
    0x81, 0x7d, 0xa0, 0x00, 0x94, 0x35, 0x77, 0xeb, 0x42,   # CMP dword ptr [EBP-0x60],0x77359400
    0xeb                                                    # JMP
]
