[package]
name = "udp-ping"
version = "0.1.0"
authors = ["ivfranco <ivfranco33@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
internet-checksum = "=0.2.0"
random-fast-rng = "=0.1.1"