[package]
name = "bdd"
version = "0.1.0"
authors = ["ivfranco <ivfranco33@outlook.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.17.0"

[dependencies]
boolean_expression = "0.3.8"
lalrpop-util = "0.17.0"
regex = "0.2.1"
