[package]
name = "file-copy-pipe"
version = "0.1.0"
authors = ["ivfranco <ivfranco@smoug.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "^0.15"