[package]
name = "searching"
version = "0.1.0"
authors = ["ivfranco <ivfranco33@outlook.com>"]
edition = "2018"

[dependencies]
pathfinding = "^1.1"
rand = "^0.6"
petgraph = "^0.4"
num-traits = "^0.2"
indexmap = "^1.0"
ordered-float = "^1.0"